require 'fileutils'
require 'csv'
require_relative 'rom_utilities'
require_relative 'locales'
require_relative 'Table'
require_relative 'Images'
require_relative 'XP'
require_relative 'quests'
require_relative 'armor'
require_relative 'weapons'
require_relative 'addpower'
require_relative 'runes'
require_relative 'suits'
require_relative 'refines'
require_relative 'magic'
require_relative 'magicCollection'
require_relative 'food'
require_relative 'cards'
require_relative 'titles'
require_relative 'voc'


