-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/charplan/localization/
--]]

Charplan.L =
--@localization(locale="zhCN", format="lua_table", handle-unlocalized="ignore")@

Charplan.L.STAT_SHORTS =
--@localization(locale="zhCN", namespace="STAT_SHORTS", format="lua_table", handle-unlocalized="ignore")@

Charplan.L.STAT_NAMES =
--@localization(locale="zhCN", namespace="STATS", format="lua_table", handle-unlocalized="ignore")@
