-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/charplan/localization/
--]]

CP.L =
--@localization(locale="deDE", format="lua_table", handle-unlocalized="ignore")@
--@do-not-package@
{}
--@end-do-not-package@


CP.L.STAT_SHORTS =
--@localization(locale="deDE", namespace="STAT_SHORTS", format="lua_table", handle-unlocalized="ignore")@
--@do-not-package@
nil
--@end-do-not-package@

CP.L.STAT_NAMES =
--@localization(locale="deDE", namespace="STATS", format="lua_table", handle-unlocalized="ignore")@
--@do-not-package@
nil
--@end-do-not-package@

--@do-not-package@
----- DEVELOPER VERSION
CP.L ={
    TITLE_EMPTY = "<unbenannt>",
    MENU_TITLE = "Menu",
    MENU_IMPORT= "Ausrüstung importieren",
    MENU_LOAD= "Ausrüstung laden",
    MENU_SAVE= "Ausrüstung speichern",
    MENU_SAVEAS= "Ausrüstung speichern unter…",
    MENU_COMPARE= "Vergleichswerte",
    MENU_DEL= "Speicherstand löschen",
	MENU_CLEARALL = "Ausrüstung leeren",

    DLG_WAIT_INV= "Bitte warten während ihre Ausrüstung übertragen wird",
    DLG_SAVENAME= "Namen eingeben",
    ENUMERATE_CANCELED = "Übertragung abgebrochen",

    CONTEXT_MENU = "Zum Plan hinzufügen",
    CONTEXT_PIMPME= "Pimp: %s",
    CONTEXT_SEARCH= "Suche",
    CONTEXT_SHARE = "Kopiere Werte zu…",
    CONTEXT_CLEAR = "Leeren",

    ERROR_NOSLOT = "Ein freier Rucksack platz wird für das Importieren benötigt.",
    ERROR_PICKEDUPITEM = "Beim Übertragen ist ein Fehler aufgetreten! Bitte prüfen Sie ihre Ausrüstung!",
    ERROR_SEARCH_SKIN = "«%s»! Skin konnte nicht eindeutig erkannt werden und könnte falsch sein!",
    ERROR_NO_VALID_ITEM= "Kein ausrüstbarer Gegenstand.",

    PIMP_STAT = "Stat %i",
    PIMP_RUNE = "Rune %i",
    PIMP_PLUS = "Plus",
    PIMP_FILTER1 = "<Name>",
    PIMP_FILTER2 = "<Stat1>",
    PIMP_FILTER3 = "<Stat2>",
    PIMP_FILTER4 = "min",
    PIMP_COPY = "Kopiere zu…",
    PIMP_COPY_TO_ALL = "… allen Gegenständen",
    PIMP_CLEAR = "Löschen",
    PIMP_CLEAR_TIP = "benötigt Doppelklick",

    SEARCH_TITLE = "Gegenstandssuche",
    SEARCH_BASE_STATS = "Dmg/Def",
    SEARCH_STATS = "Stats",
    SEARCH_NOSTATLESS = "Kostüme ausblenden",
    SEARCH_NOSTATLESS_TIP = "Blended Gegenst. ohne Zusatzwerte aus (bsp: Flügel, Kostüme)",
	SEARCH_ONLYSET = "Nur Item-Sets",
    SEARCH_TYPE = "Type",
    SEARCH_POWER_MODIFY = "%i Dura",

    SEARCH_USE_SLOT1 = "In Slot1",
    SEARCH_USE_SLOT2 = "In Slot2",
    SEARCH_CONTEXT_TAKE = "Gegenstand anlegen",
    SEARCH_CONTEXT_SUIT = "Ganzes Set anlegen",
    SEARCH_CONTEXT_SKIN = "Skin übernehmen",
    SEARCH_CONTEXT_WEB = "Im Webbrowser öffnen",
    SEARCH_WEBSITE = "http://de.runesdatabase.com/item/%i",

    BY_CLASS = "Base",
    BY_SKILL = "Skill",
    BY_SET = "Sets",

    STAT_SHORTS= {},
    STAT_NAMES= {},
}
--@end-do-not-package@