-- this file is NOT USED .. it's just a provide a overview

-----------------------------
-- STAT LIST
CP.DB.Stats={ -- name = TEXT("SYS_WEAREQTYPE_xxx"
    0 , -- "Keine Wirkung.",
    1 , -- "Haltbarkeit",
    2 , -- "Stärke",
    3 , -- "Ausdauer",
    4 , -- "Intelligenz",
    5 , -- "Weisheit",
    6 , -- "Geschicklichkeit",
    7 , -- "Alle Attribute",
    8 , -- "Maximale LP",
    9 , -- "Maximale MP",
    10 , -- "LP-Erholung",
    11 , -- "MP-Erholungsrate",
    12 , -- "Physischer Angriff",
    13 , -- "Verteidigung",
    14 , -- "Magische Verteidigung",
    15 , -- "Magischer Angriff",
    16 , -- "Präzision",
    17 , -- "Ausweichrate",
    18 , -- "Physische kritische Trefferrate",
    19 , -- "% Kritischer Schaden",
    20 , -- "Magische kritische Trefferrate",
    21 , -- "% Kritischer magischer Schaden",
    22 , -- "Parieren",
    23 , -- "% Angriffsgeschwindigkeit",
    24 , -- "% Bewegungsgeschwindigkeit",
    25 , -- "Schaden",
    26 , -- "Alle Widerstandskräfte",
    27 , -- "Erd-Widerstandskraft",
    28 , -- "Wasser-Widerstandskraft",
    29 , -- "Feuer-Widerstandskraft",
    30 , -- "Wind-Widerstandskraft",
    31 , -- "Licht-Widerstandskraft",
    32 , -- "Dunkelheits-Widerstandskraft",
    33 , -- "% verringerter MP-Verbrauch",
    34 , -- "% Erfahrungsrate",
    35 , -- "% Droprate",
    36 , -- "% Nebenhand-Präzision",
    37 , -- "% Nebenhand-Schadensrate",
    38 , -- "% Rüstungsschutz-Bonus",
    39 , -- "% Kettenschutz-Bonus",
    40 , -- "% Lederschutz-Bonus",
    41 , -- "% Stoffschutz-Bonus",
    42 , -- "% Robenschutz-Bonus",
    43 , -- "% Schildschutz-Bonus",
    44 , -- "% Magiekraft",
    45 , -- "% Erdmagiekraft",
    46 , -- "% Wassermagiekraft",
    47 , -- "% Feuermagiekraft",
    48 , -- "% Windmagiekraft",
    49 , -- "% Lichtmagiekraft",
    50 , -- "% Dunkelheitsmagiekraft",
    51 , -- "% Zauberverzögerung",
    52 , -- "% Fernkampfwaffen-Schadensrate",
    53 , -- "% Bogen-Schadensrate",
    54 , -- "% Armbrust-Schadensrate",
    55 , -- "% Feuerwaffen-Schadensrate",
    56 , -- "% Nahkampfwaffen-Schadensrate",
    57 , -- "% Waffenlos-Schadensrate",
    58 , -- "% Schwert-Schadensrate",
    59 , -- "% Dolch-Schadensrate",
    60 , -- "% Stab-Schadensrate",
    61 , -- "% Axt-Schadensrate",
    62 , -- "% Einhandhammer-Schadensrate",
    63 , -- "% Zweihandschwert-Schadensrate",
    64 , -- "% Zweihandstab-Schadensrate",
    65 , -- "% Zweihandaxt-Schadensrate",
    66 , -- "% 'Beidhändiger Hammer'-Schadensrate",
    67 , -- "% Feuerwaffen-Schadensrate",
    68 , -- "% Fernangriffsverzögerung",
    69 , -- "% Bogen-Angriffsverzögerung",
    70 , -- "% Armbrust-Angriffsverzögerung",
    71 , -- "% Feuerwaffen-Angriffsverzögerung",
    72 , -- "% Nahkampf-Angriffsverzögerung",
    73 , -- "% Waffenlos-Angriffsverzögerung",
    74 , -- "% Schwert-Angriffsverzögerung",
    75 , -- "% Dolch-Angriffsverzögerung",
    76 , -- "% Stab-Angriffsverzögerung",
    77 , -- "% Axt-Angriffsverzögerung",
    78 , -- "% Einhandhammer\n-Angriffsverzögerung",
    79 , -- "% Zweihandschwert-Angriffsverzögerung",
    80 , -- "% Zweihandstab-Angriffsverzögerung",
    81 , -- "% Zweihandaxt-Angriffsverzögerung",
    82 , -- "% 'Beidhändiger Hammer'-Angriffsverzögerung",
    83 , -- "% Feuerwaffen-Angriffsverzögerung",
    84 , -- "Fähigkeit: Waffenlos",
    85 , -- "Fähigkeit: Schwert",
    86 , -- "Fähigkeit: Dolch",
    87 , -- "Fähigkeit: Stab",
    88 , -- "Fähigkeit: Axt",
    89 , -- "Fähigkeit: Einhandhammer",
    90 , -- "Fähigkeit: Zweihandschwert",
    91 , -- "Fähigkeit: Zweihandstab",
    92 , -- "Fähigkeit: Zweihandaxt",
    93 , -- "Fähigkeit: Beidhändiger Hammer",
    94 , -- "Fähigkeit: Feuerwaffe",
    95 , -- "Fähigkeit: Bogen",
    96 , -- "Fähigkeit: Armbrust",
    97 , -- "Fähigkeit: Feuerwaffe",
    98 , -- "Fähigkeit: Wurfwaffen",
    99 , -- "Fähigkeit: Platte",
    100 , -- "Fähigkeit: Kettenrüstung",
    101 , -- "Fähigkeit: Leder",
    102 , -- "Fähigkeit: Kleidung",
    103 , -- "Fähigkeit: Robe",
    104 , -- "Fähigkeit: Schild",
    105 , -- "Fähigkeit: Talisman",
    106 , -- "Fähigkeit: Zweihandwaffe",
    107 , -- "Waffenlos-Fertigkeit",
    108 , -- "Schwert-Fertigkeit",
    109 , -- "Dolch-Fertigkeit",
    110 , -- "Stab-Fertigkeit",
    111 , -- "Axt-Fertigkeit",
    112 , -- "Hammer-Fertigkeitssteigerung",
    113 , -- "Zweihandschwert-Fertigkeit",
    114 , -- "Stab-Fertigkeit",
    115 , -- "Zweihandaxt-Fertigkeit",
    116 , -- "Zweihandhammer-Fertigkeit",
    117 , -- "Feuerwaffen-Fertigkeit",
    118 , -- "Bogen-Fertigkeit",
    119 , -- "Armbrust-Fertigkeit",
    120 , -- "Feuerwaffen",
    121 , -- "Verteidigung",
    122 , -- "Schmiedehandwerk",
    123 , -- "Schreinerhandwerk",
    124 , -- "Rüstungsherstellung",
    125 , -- "Schneiderhandwerk",
    126 , -- "Kochfertigkeit",
    127 , -- "Alchemie",
    128 , -- "% Schmiede-Erfolgsrate",
    129 , -- "% Schreinerei-Erfolgsrate",
    130 , -- "% Rüstungsschmied-Erfolgsrate",
    131 , -- "% Schneiderei-Erfolgsrate",
    132 , -- "% Koch-Erfolgsrate",
    133 , -- "% Alchemie-Erfolgsrate",
    134 , -- "% physische Angriffe",
    135 , -- "% Verteidigung",
    136 , -- "% Stehlen",
    137 , -- "% Gold-Beute",
    138 , -- "% Aggro",
    139 , -- "% Zornerholung",
    140 , -- "% Fokuserholung",
    141 , -- "% Energieerholung",
    142 , -- "% Magieabsorption",
    143 , -- "% Verteidigungsabsorption",
    144 , -- "% Heilungsabsorption",
    145 , -- "Magieabsorption",
    146 , -- "Verteidigungsabsorption",
    147 , -- "Heilungsabsorption",
    148 , -- "Magischer Schaden",
    149 , -- "% Heilung",
    150 , -- "Heilung",
    151 , -- "Fernkampfwaffen-Reichweite",
    152 , -- "Holzfällerfertigkeit",
    153 , -- "Kräutersammelfertigkeit",
    154 , -- "Bergbaufertigkeit",
    155 , -- "Fischereifertigkeit",
    156 , -- "Holzfäller-Beuterate",
    157 , -- "Kräutersammel-Beuterate",
    158 , -- "Bergbau-Beuterate",
    159 , -- "Angel-Beuterate",
    160 , -- "Sammel-Erfolgsrate",
    161 , -- "% Stärke",
    162 , -- "% Ausdauer",
    163 , -- "% Intelligenz",
    164 , -- "% Weisheit",
    165 , -- "% Geschicklichkeit",
    166 , -- "% Alle Hauptattribute",
    167 , -- "% LP-Maximums",
    168 , -- "% MP-Maximums",
    169 , -- "% Reitgeschwindigkeit",
    170 , -- "% Magische Verteidigung",
    171 , -- "% Magische Angriffskraft",
    172 , -- "Schildblockrate",
    173 , -- "% Schaden",
    174 , -- "Sekundärklassenerfahrung",
    175 , -- "% TP-Erfahrung",
    176 , -- "% Holzfäller-Erfolgsrate",
    177 , -- "% Kräutersammel-Erfolgsrate",
    178 , -- "% Bergbau-Erfolgsrate",
    179 , -- "% Fischerei-Erfolgsrate",
    181 , -- "% Chance auf zusätzliche Attacke",
    182 , -- "Physischer kritischer Widerstand",
    183 , -- "Magischer kritischer Widerstand",
    184 , -- "Erdschaden",
    185 , -- "Wasserschaden",
    186 , -- "Feuerschaden",
    187 , -- "Windschaden",
    188 , -- "Lichtschaden",
    189 , -- "Dunkler Schaden",
    190 , -- "Sprung-Fähigkeit",
    191 , -- "Magieschadenspunkte",
    192 , -- "% magische Schadensrate",
    193 , -- "Schildblock überwinden",
    194 , -- "Parieren überwinden",
    195 , -- "Magische Präzision",
    196 , -- "Magie-Resistenz",
    197 , -- "% Präzision bei physischen Angriffen",
    198 , -- "Ausweichrate",
    199 , -- "% Magische Präzision",
    200 , -- "Magische Widerstandsrate",
    201 , -- "Sammelmenge",
    202 , -- "Sammelgeschwindigkeit",
    203 , -- "Sammelerfahrung",
    204 , -- "Schaden gegen Spieler und Begleiter",
    205 , -- "Schaden gegen NPCs",
    206 , -- "% Schaden von Spielern",
    207 , -- "% Schaden von Monstern",
    208 , -- "Angriffskraft von Flächenzaubern",
    209 , -- "Widerstand gegen AC-Zauber",
    210 , -- "Herstellungsgeschwindigkeit",
    211 , -- "Herstellungserfahrung",
    212 , -- "Erhöhung der EP nach Spielerfolg",
    213 , -- "Erhöhung der TP nach Spielerfolg",
}





